---
title: Valley Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: The Valley Discord Server
discord: egg-irl
url: https://the-valley-discord.github.io
description: 'The Official Valley Discord Blog

'
favicon: "./favicon.ico"
show_excerpts: false
moving:
  avatar_url: https://avatars2.githubusercontent.com/u/54571093
  about_you: The official egg_irl community server.
  date_format: "%b %d"
  back_to: Home
  social_links:
    github: The-Valley-Discord
    discord: egg-irl
    rss: RSS
    reddit: "/r/egg-irl"
remote_theme: huangyz0918/moving
plugins:
- jekyll-feed
- jekyll-seo-tag
permalink: pretty
